### PR TITLE
Add basic account operations

### PR DESCRIPTION
**Pull request by courajs**
This adds:
- show page for individual accounts
- deleting an account (via the show page)
- adding a new account (via the account list page)

### CODE REVIEW

**Comment by courajs** [comment]
@gr2m take a peek?

**Comment by gr2m** [comment]
sorry for the delay, slipped through my reviews in the past days. Checking now :)

**Comment by gr2m** [comment]
Can you add a back button to the account detail page? 

screen shot 2016-05-31 at 22 46 49

Otherwise it’s great, cool to see things coming along :)

**Comment by gr2m** [comment]
Oh, and can we add some kind of confirmation to avoid accidental deletion?

**Comment by courajs** [comment]
@gr2m updated!

**Comment by gr2m** [comment]
Perfect, LGTM! Ping @hoodiehq/maintainers for 2nd review 👀 

### Local setup

`hoodie-admin` requires [bower](http://bower.io/) (`npm install --global bower`)

```
git clone git@github.com:hoodiehq/hoodie-admin.git
cd hoodie-admin
npm install
bower install
npm start
```

**Comment by HipsterBrown** [comment]
Great work @courajs! Everything works as described. :clap:

One note for creating new accounts. **Could a button be added allowing admins to show the password they're typing in that field?** It can lead to less mistakes and more confidence that the admin is typing the correct password. **It's not necessary for this build but would be nice to add to the MVP.** 

LGTM 🚀

**Comment by gr2m** [comment]
Thanks @HipsterBrown, I created a follow up issue here for later: https://github.com/hoodiehq/hoodie-admin/issues/10

**Pull request merged**
