### PR TITLE
show all hoodie-account data in account template

### PR DESCRIPTION
**Pull request by fredguth**
This is a minor change.  But now basic feature set of hoodie-admin is done:
√ login as admin
√manage user accounts (add and remove account)
√ access user data

### CODE REVIEW

**Review by gr2m — APPROVED** [review]

**Comment by gr2m** [comment]
This looks good, thanks 👍 

Right now we can only view accounts, we cannot change them. Also there are a few special properties in accounts. Here’s what I’d suggest to do next
1. Add username change feature
2. Add password change feature
3. Add password reset feature
4. Show profile properties as a table with key / value, value itself might be an object, so this could be nested. For example, there could be properties like `profile.address.street`. Allow to add / remove / change properties
5. Show roles (`.roles`) . Allow to add / remove roles. Roles is an array of strings. Roles are used for access management and feature flags (e.g. a "pro-plan" role after a user signed up for a paid plan)
6. List tokens (`.tokens`). Allow to remove tokens. Tokens are used for password reset, email confirmations, one-time logins, etc. They have an id, a type and an expiration date.

**Comment by fredguth** [comment]
@gregor.  
About item (4), I see 2 different approaches:
a) Firebase approach: create a tree (https://www.evernote.com/l/AZQ34mmVBppCQqyaN90MFID2Be5qZIVqbQkB/image.png)

b)Parse approach: a menu tree and tables
https://www.evernote.com/l/AZSLZVqPGLFD1Zhz9bQlz3CHn3LqZS-pyVEB/image.png

What have you imagined?

**Comment by gr2m** [comment]
Thanks for doing the research, both parse and firebase are definitely projects we can learn from to make our admin dashboard great :)

We didn’t yet give a lot of thought on how to design the account edit forms. I think for now we would be good to have different sections for

```
# {username}

created: {createadAt}
signed up: {signedUpAt}
last update: {updatedAt}

[change username], [change password], [reset password], [delete account]

## Roles

list roles as bullet points, allow to add / remove

## Tokens

Show table of tokens with id, type, timestamp, expiration, and meta data. Allow to delete

## Profile

Show a table with key / value. For nested properties, we can simply do JSON for now and come up with something more sophisticated later?
```

**Comment by fredguth** [comment]
@gr2m This is long due... but I was wondering if what you mean is something like this:
hoodie_admin
When you click in the user, it opens details of profile. 
I don't know about Roles and Tokens in Hoodie, though.

**Comment by gr2m** [comment]
looks good to me :)

**Pull request merged**
